const MENU = {
    coffee: [
        {
            title: 'Irish coffee',
            description: 'Fragrant black coffee with Jameson Irish whiskey and whipped milk',
            price: '7.00',
            image: 'coffee-1',
            size: ['200 ml', '300 ml', '400 ml'],
            additives: ['sugar', 'cinnamon', 'syrup'],
        },
        {
            title: 'Kahlua coffee',
            description: 'Classic coffee with milk and Kahlua liqueur under a cap of frothed milk',
            price: '7.00',
            image: 'coffee-2',
            size: ['200 ml', '300 ml', '400 ml'],
            additives: ['sugar', 'cinnamon', 'syrup'],
        },
        {
            title: 'Honey raf',
            description: 'Espresso with frothed milk, cream and aromatic honey',
            price: '5.50',
            image: 'coffee-3',
            size: ['200 ml', '300 ml', '400 ml'],
            additives: ['sugar', 'cinnamon', 'syrup'],
        },
        {
            title: 'Ice cappuccino',
            description: 'Cappuccino with soft thick foam in summer version with ice',
            price: '5.00',
            image: 'coffee-4',
            size: ['200 ml', '300 ml', '400 ml'],
            additives: ['sugar', 'cinnamon', 'syrup'],
        },
        {
            title: 'Espresso',
            description: 'Classic black coffee',
            price: '4.50',
            image: 'coffee-5',
            size: ['200 ml', '300 ml', '400 ml'],
            additives: ['sugar', 'cinnamon', 'syrup'],
        },
        {
            title: 'Latte',
            description: 'Espresso coffee with the addition of steamed milk and dense milk foam',
            price: '5.50',
            image: 'coffee-6',
            size: ['200 ml', '300 ml', '400 ml'],
            additives: ['sugar', 'cinnamon', 'syrup'],
        },
        {
            title: 'Latte macchiato',
            description: 'Espresso with frothed milk and chocolate',
            price: '5.50',
            image: 'coffee-7',
            size: ['200 ml', '300 ml', '400 ml'],
            additives: ['sugar', 'cinnamon', 'syrup'],
        },
        {
            title: 'Coffee with cognac',
            description: 'Fragrant black coffee with cognac and whipped cream',
            price: '6.50',
            image: 'coffee-8',
            size: ['200 ml', '300 ml', '400 ml'],
            additives: ['sugar', 'cinnamon', 'syrup'],
        },
    ],
    tea: [
        {
            title: 'Moroccan',
            description: 'Fragrant black tea with the addition of tangerine, cinnamon, honey, lemon and mint',
            price: '4.50',
            image: 'tea-1',
            size: ['200 ml', '300 ml', '400 ml'],
            additives: ['sugar', 'lemon', 'syrup'],
        },
        {
            title: 'Ginger',
            description: 'Original black tea with fresh ginger, lemon and honey',
            price: '5.00',
            image: 'tea-2',
            size: ['200 ml', '300 ml', '400 ml'],
            additives: ['sugar', 'lemon', 'syrup'],
        },
        {
            title: 'Cranberry',
            description: 'Invigorating black tea with cranberry and honey',
            price: '5.00',
            image: 'tea-3',
            size: ['200 ml', '300 ml', '400 ml'],
            additives: ['sugar', 'lemon', 'syrup'],
        },
        {
            title: 'Sea buckthorn',
            description: 'Toning sweet black tea with sea buckthorn, fresh thyme and cinnamon',
            price: '5.50',
            image: 'tea-4',
            size: ['200 ml', '300 ml', '400 ml'],
            additives: ['sugar', 'lemon', 'syrup'],
        },
    ],
    dessert: [
        {
            title: 'Marble cheesecake',
            description: 'Philadelphia cheese with lemon zest on a light sponge cake and red currant jam',
            price: '3.50',
            image: 'dessert-1',
            size: ['50 mg', '100 mg', '200 mg'],
            additives: ['Berries', 'Nuts', 'Jam'],
        },
        {
            title: 'Red velvet',
            description: 'Layer cake with cream cheese frosting',
            price: '4.00',
            image: 'dessert-2',
            size: ['50 mg', '100 mg', '200 mg'],
            additives: ['Berries', 'Nuts', 'Jam'],
        },
        {
            title: 'Cheesecakes',
            description:
                'Soft cottage cheese pancakes with sour cream and fresh berries and sprinkled with powdered sugar',
            price: '4.50',
            image: 'dessert-3',
            size: ['50 mg', '100 mg', '200 mg'],
            additives: ['Berries', 'Nuts', 'Jam'],
        },
        {
            title: 'Creme brulee',
            description: 'Delicate creamy dessert in a caramel basket with wild berries',
            price: '4.00',
            image: 'dessert-4',
            size: ['50 mg', '100 mg', '200 mg'],
            additives: ['Berries', 'Nuts', 'Jam'],
        },
        {
            title: 'Pancakes',
            description: 'Tender pancakes with strawberry jam and fresh strawberries',
            price: '4.50',
            image: 'dessert-5',
            size: ['50 mg', '100 mg', '200 mg'],
            additives: ['Berries', 'Nuts', 'Jam'],
        },
        {
            title: 'Honey cake',
            description: 'Classic honey cake with delicate custard',
            price: '4.50',
            image: 'dessert-6',
            size: ['50 mg', '100 mg', '200 mg'],
            additives: ['Berries', 'Nuts', 'Jam'],
        },
        {
            title: 'Chocolate cake',
            description: 'Cake with hot chocolate filling and nuts with dried apricots',
            price: '5.50',
            image: 'dessert-7',
            size: ['50 mg', '100 mg', '200 mg'],
            additives: ['Berries', 'Nuts', 'Jam'],
        },
        {
            title: 'Black forest',
            description: 'A combination of thin sponge cake with cherry jam and light chocolate mousse',
            price: '6.50',
            image: 'dessert-8',
            size: ['50 mg', '100 mg', '200 mg'],
            additives: ['Berries', 'Nuts', 'Jam'],
        },
    ],
};
